# Stage 1: Build da aplicação
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Imagem final
FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Variáveis de ambiente para configuração do banco de dados
ENV SPRING_DATASOURCE_URL=jdbc:mysql://bom9n6o99sz2sm3vgqwq-mysql.services.clever-cloud.com/bom9n6o99sz2sm3vgqwq
ENV SPRING_DATASOURCE_USERNAME=uyo6kx5tiy7u8lrg
ENV SPRING_DATASOURCE_PASSWORD=JwTzQc8BGPCCit3ewIHM

# Configurações do pool de conexões
ENV SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=2
ENV SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE=1
ENV SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT=30000
ENV SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT=120000
ENV SPRING_DATASOURCE_HIKARI_MAX-LIFETIME=300000

# Configurações do Hibernate
ENV SPRING_JPA_PROPERTIES_HIBERNATE_GENERATE_STATISTICS=false
ENV SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE=25
ENV SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS=true
ENV SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES=true
ENV SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_PROVIDER_DISABLES_AUTOCOMMIT=true

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]